### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by Mateoo303** [sameemul-haque/dotfiles#3]
Which font/fonts do you use for waybar?

**Comment by sameemul-haque** [comment]
@Mateoo303 
Material Design Icons and JetBrainsMono Nerd Font

https://github.com/sameemul-haque/dotfiles/blob/95938eec2da691a0cc6773881049c92e252d63ad/.config/waybar/style.css#L5

If you don't have any further questions, you can close this issue now
