### ISSUE TITLE
Missing Main.qml File for SDDM

### ISSUE THREAD

**Issue by Agent123983** [sameemul-haque/dotfiles#4]
Hey friend, trying to load the theme for SDDM but I'm getting an error saying that sugar-candy is missing the Main.qml file and can not load. I can't find much about this error but is there a step I missed when installing this theme?

Thank you!

**Comment by sameemul-haque** [comment]
Hi, @Agent123983 


It looks like you might have missed installing the `sddm-sugar-candy-git` package from the AUR. Please try installing it and see if that resolves the issue.

- https://aur.archlinux.org/packages/sddm-sugar-candy-git
- https://wiki.archlinux.org/title/SDDM#Configuration
- https://wiki.archlinux.org/title/SDDM#Theme_settings

You can close this issue if it fixes the problem.
Thanks

**Comment by Agent123983** [comment]
Sure enough that fixed it, thank you!
